modLoader="lowcodefml"
showAsResourcePack = false
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="powerrangers"
version="1.0.0"
logoFile = "logo.png"
logoBlur = false
displayName="PowerRangers"
description='''
powerrangers
'''

[[dependencies.powerrangers]]
modId = "palladium"
mandatory = true
versionRange = "[4.4.1,)"
ordering = "NONE"
side = "BOTH"
